# Add 'repo' label to any root file changes
repo:
  - ./*
  
# Add '@domain/core' label to any change within the 'core' package
services:
  - pkg/services/**
  - internal/services/**
  - cmd/services/**

protos:
  - build/protos/**
  - protos/**

k8s:
  - build/manifest/**/*

docker:
  - /**/*.Dockerfile

test:
  - test/**
  - /**/*_test.go