openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
paths:
  /dumpme:
    get:
      responses:
        '200':
          description: OK
          content:
            application/text:
              schema:
                type: string
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref:
                  "#/components/ErrorMessage"
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
        errorMessage:
          type: string
        code:
          type: number
        AdditionalData:
          type: array