name: Build Todo Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image based on Google Distroless
      run: docker build services/todo --file services/todo/build/container/Dockerfile 
